#!/bin/sh

MYDIR="`dirname \"$0\"`"
MYDIR="`( cd \"$MYDIR\" && pwd )`"

ln -s $MYDIR/.zshrc $HOME/.zshrc
ln -s $MYDIR/.zshenv $HOME/.zshenv
ln -s $MYDIR/.aliases $HOME/.aliases
ln -s $MYDIR/.pass.zsh-completion $HOME/.pass.zsh-completion
